### ISSUE TITLE
Why does OIDCAuthenticationFilter have a protected constructor ? 

### ISSUE THREAD

**Issue by sbrown44** [mitreid-connect/mitreid-connect.github.com#1]
Hi

Why does OIDCAuthenticationFilter have a protected constructor ? Makes it hard to use this as a bean using spring java config. 

On a related note, why is  FILTER_PROCESSES_URL final static and not  a property passed in via a constructor ?

**Comment by wikkim** [comment]
Hi,
This has already been addressed in the main project:
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/729

BTW, for future reference you would probably be better served posting issues to the main project (https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server).
